python: Add exception for wmfs.init() if wmfs is not running, an exception is called like:   In [2]: wmfs.init()   ---------------------------------------------------------------------------   error                                     Traceback (most recent call last)
  /usr/home/marc/<ipython console> in <module>()

  error: WMFS not running?

Signed-off-by: Marc Lagrange <marc@shebang.sangor>