python: The right exception is called, WmfsInitError instead of error. a wmfs.WmfsInitError is available with a wmfs.WmfsInitError.message containing message error.
In [2]: wmfs.init()
---------------------------------------------------------------------------
WmfsInitError                             Traceback (most recent call last)

/usr/home/marc/<ipython console> in <module>()

WmfsInitError: WMFS not running?

In [3]: try:
   ...:     wmfs.init()
   ...: except wmfs.WmfsInitError, e:
   ...:     print 'Error: '+e.message
   ...:
Error: WMFS not running?

Signed-off-by: Marc Lagrange <marc@shebang.sangor>